### ISSUE TITLE
Does the order of applying orientation matrix and upisup affine shape matrix matter?

### ISSUE THREAD

**Issue by IQ17** [ducha-aiki/affnet#14]
Hi, I am confused if we should apply upisup affine shape matrix and then apply the orientation matrix to the patch?

The upisup affine shape matrix will keep only keep the y-axis of patch, so say if patch1 in image1 is an arraw pointing to the left, while the patch2 in image1 has the arraw pointing up. After applying the upisup affine shape matrix, the arraw in patch1 will be twisted while the the arraw in patch2 should remained up. then we apply the orientation matrix to both patch1 and patch2, even the ground truth orientation matrices will not make them similiar, except for the case where upisup affine shape matrix applyed to the patch1 is an identity matrix. 

So I am thinking, should not we apply orientation matrix first to rotate both patches to the same direction, and then apply the upisup affine shape matrix to adjust the appeareance?

**Comment by IQ17** [comment]
By the way, could you point a reference for the affine shape parameterization in section 2.1 in paper? thanks!

**Comment by ducha-aiki** [comment]
Sorry, could you please rephrase your question? I have read two times and still does not get it... But you mean train on Brown patches or test as feature extractor? 
Also I don`t get the reference to what? Source code?

**Comment by IQ17** [comment]
![default](https://user-images.githubusercontent.com/5336719/46356424-513a4480-c695-11e8-9a70-50d49429e07f.PNG)

I am talking about this formula from section 2.1 in your ECCV18 paper. 

In this formula, there are two matrices, one is the orientation matrix, and the other is an upisup affine shape matrix. I am asking that does the order of two matrices matter? could you point a reference for the paper/book where formula comes? thanks!

**Comment by IQ17** [comment]
![default](https://user-images.githubusercontent.com/5336719/46356853-30beba00-c696-11e8-9509-83087a1f5ec7.PNG)

As you mentioned in the paper, the upisup affine shape matrix preserves the vertical direction. So in the example I descriped in the original question, should not we apply orientation matrix before upisup affine shape matrix?

**Comment by ducha-aiki** [comment]
@IQ17 there is not book for this, this simple goes from playing with affine matrix decomposition. See also this thread 
https://github.com/ducha-aiki/affnet/issues/13#issuecomment-426236002

Yes, order matters a lot. There are two orientation matrices, one is in your screenshot and another is incorporated into (a11, 0; a21 a22). One matrix is for (circular) patch orientation. Another rotation matrix is for ellipse shape, meaning where long axis looking.

>should not we apply orientation matrix before upisup affine 

No. Because if we apply before, then up-is-up kills it. Vertical orientation is preserved regarding original image, where feature was detected. Image orientation can be arbitrary. 
Instead, we want to detect (unoriented) ellipses in both image, then rotate them according, hoping that it would result in similarly looking patches.

**Comment by ducha-aiki** [comment]
You may ask then, why do we need "up is up" at all? At test time we don`t need it actually, since the learned OriNet should be able to estimate canonical orientation from any initial position given the patch.

However, in training time we know only our augmentation angles for patches p1 and p2, which we need to compensate accordingly. However, our estimate of the affine shape may contain itself some (unknown) rotation. To cancel it we apply up-is-up

**Comment by IQ17** [comment]
Thanks for the clearly answering!
