### ISSUE TITLE
Extract Patches

### ISSUE THREAD

**Issue by ghost** [ducha-aiki/affnet#3]
Dear/Dmytro
I wonder what's the difference between "extract_patches_from_pyr" (method in SparseImgRepresenter.py) and extract_patches(method in LAF.py) ??
Thanks in advance

**Comment by ghost** [comment]
also if possible could you tell me if I can use one of these patches to be feed to hard_net ++ to be able to describe an image then use matching brute force matcher on the description

**Comment by ducha-aiki** [comment]
extract_patches just extract patches from image. But this is bad practice in general, because if you extract big patches, then there will be lots of sampling artifacts. Therefore, one constructs scale pyramid and extracts from it -- from appropriate level of pyramid. https://en.wikipedia.org/wiki/Pyramid_(image_processing)

Sure, you can feed this patches to HardNet++, just make sure that they have needed size: 32x32

**Comment by ghost** [comment]
so from "extract_patches_from_pyr" I can get a patch around each affine covariant feature or they are patches from different part of the image (not necessarily be around covariant feature)

**Comment by ducha-aiki** [comment]
I am afraid that don`t understand your question. 
extract_patches_from_pyr gives patches around features, which you provide as an input.

**Comment by ghost** [comment]
Thanks for the help :+1:

**Comment by ducha-aiki** [comment]
@RamadanAhmedRamadan you might be interested in this
https://github.com/ducha-aiki/mods-light-zmq
It integrates pytorch AffNet and HardNet with state-of-the art C++ matching code, as well as off-the-shell feature extraction
